[workspace]
resolver = "2"
members = [
    "hyperborealib",
    "hyperborea-server",
    "hyperbox",
    "hyperelm",
    "hyperchat"
]

[profile.release]
strip = true
lto = true
opt-level = 3

[profile.profiling]
inherits = "release"
strip = false
debug = true
