[package]
name = "hyperborea"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
anyhow = "1"

p521 = { version = "0.13.0", optional = true }

[features]
node = []
node-v1 = ["node", "dep:p521"]

default = ["node", "node-v1"]
